# Generated by Django 5.2.1 on 2025-05-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='CategoriaProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria_Producto',
            field=models.ForeignKey(db_column='CATEGORIAPRODUCTO_ID', default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.categoriaproducto'),
            preserve_default=False,
        ),
    ]
