# Generated by Django 5.2.1 on 2025-05-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria_Producto',
            new_name='categoria_Producto',
        ),
    ]
