# Generated by Django 5.2.1 on 2025-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_categoria_producto_producto_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
