# Generated by Django 5.2.1 on 2025-05-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=100)),
            ],
        ),
    ]
